# -*- mode: ruby -*-
# vi: set ft=ruby :

# http://docs.aws.amazon.com/gettingstarted/latest/wah-linux/getting-started-create-custom-ami.html

Vagrant.configure("2") do |config|
  config.vm.box = "dummy"
  config.vm.provision :shell, :path => "packages.sh"
  config.ssh.max_tries = 10

  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider :aws do |aws, override|
    aws.instance_type = "t1.micro"

    aws.region = "us-east-1"
    aws.availability_zone = "us-east-1d"
    # http://cloud-images.ubuntu.com/releases/quantal/release-20121218/
    # Ubuntu 12.10 64-bit
    aws.ami = "ami-7539b41c"
    aws.region_config "us-east-1", :ami => "ami-7539b41c"
    # aws.security_groups = ["default"]

    # https://portal.aws.amazon.com/gp/aws/securityCredentials
    # pc2
    aws.access_key_id = ""
    aws.secret_access_key = ""
    aws.keypair_name = ""

    override.ssh.private_key_path = ".pem"
    override.ssh.username = "ubuntu"
    #aws.ssh.private_key_path = ".pem"
    #aws.ssh.username = "ubuntu"
  end

end
